### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by 6nz** [Joseloll/Rawr-Logger#2]
Use this basic anti debug, at least 10x better than urs
https://github.com/6nz/python-anti-debugger

**Comment by Joseloll** [comment]
thank you will look into it lol kinda rushed this project and dont wanna make it to over powered since its a free grabber

**Comment by codeuk** [comment]
> thank you will look into it lol kinda rushed this project and dont wanna make it to over powered since its a free grabber

every python discord grabber is horrible lmao. why release this? you literally need c++ tools installed for browser_cookie to work properly. just make a cookie logger yourself

**Comment by 6nz** [comment]
you can pack all the needed stuffs

**Comment by 6nz** [comment]
plus why are u even talking when u also made token grabbers in py

**Comment by 6nz** [comment]
💀

**Comment by codeuk** [comment]
> plus why are u even talking when u also made token grabbers in py

just because I made some (months ago might I add) doesn't mean I can't talk about them.

you're just showing your immaturity and how dumb you are by saying that, and that you can 'pack all the needed *stuffs*'. have fun packing browser_cookie and a large c++ prerequisite on top of your shitty logger into one file

**Comment by 6nz** [comment]
> > plus why are u even talking when u also made token grabbers in py
> 
> just because I made some (months ago might I add) doesn't mean I can't talk about them.
> 
> you're just showing your immaturity and how dumb you are by saying that, and that you can 'pack all the needed *stuffs*'. have fun packing browser_cookie and a large c++ prerequisite on top of your shitty logger into one file

From this I can tell u dont know shit
